spring:
  application:
    name: formation-react
  banner:
    location:
      classpath: banner.txt
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: src/main/resources/V0__init.sql

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver